bugtrack/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('projects/', include('projects.urls'))
]

projects/urls.py
from django.contrib import admin
from django.urls import path,include

from projects import views

app_name = 'projects'

urlpatterns = [
    path('' , views.index_view , name = 'home'),
    path('add_project/', views.add_project, name = 'addproject')
]

users/urls.py
from django.contrib import admin
from django.urls import path,include

from users import views

app_name = 'users'

urlpatterns = [
    path('login/' , views.login_view , name ='login'),
    path("logout/", views.logout_view, name='logout'),
    path('register/' , views.register_view , name ='register'),
    path('<str:username>/' , views.profile_view , name ='profile')
]

projects/models.py
from django.db import models
from django.contrib.auth.models import User
from django.forms import ModelForm
# Create your models here.
SEVERITY = (
        ("Severe","Severe"),
        ("Moderate","Moderate"),
        ("Mild","Mild")
)

STATUS = (
        ("Open","Open"),
        ("In Progress","In Progress"),
        ("To be Re-Assigned","To be Re-Assigned"),
        ("Closed","Closed")
)


class Project(models.Model):
    team_leader = models.ForeignKey(User, on_delete=models.CASCADE)
    proj_name = models.CharField(max_length=50);
    org_name = models.CharField(max_length=50)
    domain = models.CharField(max_length=50)
    
    def __str__(self):
        return self.proj_name



class Bug(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    description = models.CharField (max_length=400)
    severity = models.CharField(max_length=50, choices=SEVERITY)
    status = models.CharField(max_length=50, choices=STATUS)

    def __str(self):
        return self.title
    


# class SaveProject():
#         model = Project
#         field = ['project_name', 'organization_name', 'project_technology']

users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save

# Create your models here.
class Profile(models.Model):
    user         = models.OneToOneField(User, on_delete=models.CASCADE)
    bio          = models.TextField()
    first_name   = models.CharField(max_length=50, blank=True)
    last_name    = models.CharField(max_length=50, blank=True)

    def __str__(self):
        return str(self.user.username) + ' Profile'


def create_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user = instance)
        print('Profile Created')

post_save.connect(create_profile, sender = User)

def update_profile(sender, instance, created, **kwargs):
    if created == False:
        instance.profile.save()
        print('Profile Updated')

post_save.connect(create_profile, sender = User)

projects/forms.py
from django import forms
from projects.models import Bug, Project

class ProjectCreationForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ['proj_name', 'org_name', 'domain']

users/forms.py
from django import forms

from users.models import Profile
from django.contrib.auth.models import User

class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username' , 'email']

class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['first_name' , 'last_name' , 'bio']

projects/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse
from django import forms


from projects.forms import ProjectCreationForm

from projects.models import Project
from django.contrib.auth.models import User

# Create your views here.
def index_view(request):
    project_list = Project.objects.all()

    context = {
        'projects' : project_list
    }
    
    return render(request, 'projects/home.html', context)


def add_project(request):
        
    form = ProjectCreationForm(request.POST)
    if request.method == 'POST':
        if form.is_valid():
            instance = form.save(commit=False)
            instance.team_leader = request.user
            instance.save()

            return redirect('projects:home')
    
    context = {
        'form':form
    }

    return render(request, 'projects/add_project.html', context)

users/views.py
from django.shortcuts import render , get_object_or_404 , reverse , redirect
from django.contrib.auth import authenticate , login , logout
from django.http import HttpResponseRedirect , HttpResponse
from django.db import IntegrityError
from django.contrib.auth.models import User 
from django.views.generic import DetailView
from django.contrib import messages

from users.models import Profile
from users.forms import ProfileUpdateForm , UserUpdateForm


# Create your views here.

def login_view(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        if user is not None:    
            login(request, user)
            return redirect('seminar:home')

        else:
            return render(request, "users/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "users/login.html")

def logout_view(request):
    logout(request)
    return redirect('seminar:home')

def register_view(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "users/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "users/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return redirect('seminar:home')
    else:
        return render(request, "users/register.html")

def profile_view(request , username):
        
    user = User.objects.get(username = username)
    querySet = Profile.objects.get(user = user)

    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST, instance=request.user.profile)

        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            return render(request, 'seminar/home.html')
    
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    u_form = UserUpdateForm(instance=user)
    p_form = ProfileUpdateForm(instance=querySet)

    context = {
        'u_form': u_form,
        'p_form': p_form,
        'profile_details' : querySet        
    }

    return render(request , 'users/profile.html' , context)

def layout(request):
    return render(request , 'users/layout.html')

projects/templates/projects/add_project.html
{% extends 'projects/base.html' %}

{% block title %}
Add Projects
{% endblock title %}

{% block addprojectform %}

<div class="container">
  <h1 class="display-4">Add Project</h1>
  <form class="mt-5" method="POST">
    {% csrf_token %}
    {{ form }}
    <button type="submit" class="btn btn-primary">Save</button>
  </form>
</div>

{% endblock%}

projects/templates/projects/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock title %}</title>
  </head>
  <body>
    
    
    {% block home %}
    {% endblock home %}

    {% block addprojectform %}
    {% endblock addprojectform %}
  </body>
</html>

projects/templates/projects/home.html
{% extends 'projects/base.html' %} {% block title %} Home {% endblock title %}
{% block home %}
<div class="container mt-3">
  <h1 class="display-4 project-title">Projects</h1>
  <table class="table mt-5">
    <thead>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Organization/Company</th>
      <th scope="col">Technology Used</th>
      <th scope="col">Team Leader</th>
    </thead>
    <tbody>
      {% for project in projects %}
      <tr>
        <th scope="row">{{forloop.counter}}</th>
        <td><a href="">{{project.proj_name}}</a></td>
        <td>{{project.org_name}}</td>
        <td>{{project.domain}}</td>
        <td>{{project.team_leader.username}}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>

  <div class="flex-container">
    <a href="{% url 'projects:addproject' %}">add project</a>
  </div>
</div>
{% endblock home %}

projects/templates/projects/navbar.html
{% extends '/base.html' %}

{% block navbar %}
<header>
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Bug Tracker</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarsExample03">
                <ul class="navbar-nav me-auto mb-2 mb-sm-0">
                    <li class="nav-item">
                        <a class="nav-link" href="#">Submit a Bug</a>
                    </li>
                </ul>
                <ul class="navbar-nav ">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="#">Dashboard</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Log Out</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
{% end block navbar %}

users/templates/users/home.html
{% extends 'users/layout.html' %}


{% block title %}
    Login
{% endblock %}

{% block body %}
<div class="container" style="margin-top:30px">
    <div class="row">
      <div class="col-sm-4">
        <h2>About Me</h2>
        <h5>Photo of me:</h5>
        <div class="fakeimg">Fake Image</div>
        <p>Some text about me in culpa qui officia deserunt mollit anim..</p>
        <h3>Some Links</h3>
        <p>Lorem ipsum dolor sit ame.</p>
        <ul class="nav nav-pills flex-column">
          <li class="nav-item">
            <a class="nav-link active" href="#">Active</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#">Disabled</a>
          </li>
        </ul>
        <hr class="d-sm-none">
      </div>
      <div class="col-sm-8">
        <h2>TITLE HEADING</h2>
        <h5>Title description, Dec 7, 2017</h5>
        <div class="fakeimg">Fake Image</div>
        <p>Some text..</p>
        <p>Sunt in culpa qui officia deserunt mollit anim id est laborum consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.</p>
        <br>
        <h2>TITLE HEADING</h2>
        <h5>Title description, Sep 2, 2017</h5>
        <div class="fakeimg">Fake Image</div>
        <p>Some text..</p>
        <p>Sunt in culpa qui officia deserunt mollit anim id est laborum consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.</p>
      </div>
    </div>
  </div>
  
  <div class="jumbotron text-center" style="margin-bottom:0;">
    <p>Footer</p>
  </div>
{% endblock %}

users/templates/users/layout.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'users/style.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@500&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <title>{% block title%}{% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="#">Webinarian</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Free Seminars</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Categories
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <a class="dropdown-item" href="#">Something else here</a>
              </div>
            </li>a
          </ul>
          <ul class="navbar-nav navbar-right">
            {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="">Host a Seminar <span class="sr-only"></span></a>
              </li>

              <li class="nav-item">
                <a class="nav-link text-capitalize active" href="{% url 'users:profile' user.username %}"><i class="ml-1 fa fa-user" aria-hidden="true"></i> {{ user.username }}<span class="sr-only"></span></a>
              </li>

              <li class="nav-item">
                  <a class="nav-link" href="{% url 'users:logout' %}">Logout <span class="sr-only"></span></a>
              </li>
            {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:login' %}">Login <span class="sr-only"></span></a>
              </li> 

              <li class="nav-item active">
                  <a class="nav-link" href="{% url 'users:register' %}">Sign Up <span class="sr-only"></span></a>
              </li>
            {% endif %}
          </ul>
        </div>
    </nav>

    {% block body %}{% endblock %}
    <footer id="sticky-footer" class="py-3 bg-dark text-white-50">
      <div class="container text-center">
        <small>Copyright &copy; Your Website</small>
      </div>
    </footer>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>

users/templates/users/login.html
{% extends 'users/layout.html' %}

{% block title %}
    Login
{% endblock %}

{% block body %}
<div class="container pb-5 mb-5W">
    <div class="row">
      <div class="col-sm-9 col-md-7 col-lg-5 pt-5 mx-auto">
        <div class="card card-signin my-5">
          <div class="card-body">

            {% if message %}
              <div class="alert alert-danger" role="alert">{{ message }}</div>
            {% endif %}

            <h5 class="card-title text-center">Sign In</h5>
            <form action="{% url 'users:login' %}" method='post' class="form-signin">
              {% csrf_token %}
              <div class="form-label-group">
                <input type="text" id="inputEmail" class="form-control" placeholder="Username" name='username' required autofocus>
                <label for="inputEmail" class='sr-only'>Username</label>
              </div>
              <br>
              <div class="form-label-group">
                <input type="password" id="inputPassword" class="form-control" placeholder="Password" name='password' required>
                <label for="inputPassword" class='sr-only'>Password</label>
              </div>
              <!---<div class="custom-control custom-checkbox mb-3">
                <input type="checkbox" class="custom-control-input" id="customCheck1">
                <label class="custom-control-label" for="customCheck1">Remember password</label>
              </div>-->
              <br>
              <input class="btn btn-lg btn-primary btn-block text-uppercase" type="submit" value='Login'></input>
              <hr class="my-4">
            </form>
            <div class='text-center'>Don't have an account? <a href="{% url 'users:register' %}">Register here.</a></div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

users/templates/users/profile.html
{% extends 'users/layout.html' %}
{% load static %}



{% block title %}
    Register
{% endblock %}

{% block body %}
<div class="jumbotron jumbotron-fluid"  style="background-image: url(https://wallpapercave.com/wp/tmx6W6N.png); background-size: cover;">
    <div class="container">
      <h1 class='display-3'>Hello {{profile_details.user.username|title}}</h1>
      <p style='font-size: larger;'>This is your profile page. You can see the progress you've made with your work and manage your projects or assigned tasks.</p>
    </div>
</div>

{% if message %}
  <div class="alert alert-danger" role="alert">{{ message }}</div>
{% endif %}

<div class='container'>
  <div class='row'>
    <div class='col-lg-4'>
      <div class="card my-3">
        <div class='card-body'>
          <h3 class='text-center pt-5 pb-3'>{{ profile_details.first_name }} {{ profile_details.last_name }}</h3>
          <p class='text-center'>{{ profile_details.bio}}</p>
          <p class='text-center py-3 text-muted'>Since: {{ profile_details.user.date_joined }}</p>
          <div class='text-center mb-4'>
            <button data-toggle="collapse" data-target="#profile_update_form" class= 'mt- btn btn-xl btn-primary'>Update Profile</button>
          </div>
        </div>
      </div>
    </div>
    <div class='col-lg-8'>
      <div class="card my-3">
        <div class="card-body">
          <h3 class='text-center pb-3'>Profile Details</h3>
          <div class="row pb-1">
            <div class="col-md-6">
                <label>Username</label>
            </div>
            <div class="col-md-6">
                <p>{{ profile_details.user.username }}</p>
            </div>
        </div>
        <div class="row pb-1">
            <div class="col-md-6">
                <label>First Name</label>
            </div>
            <div class="col-md-6">
                <p>{{ profile_details.first_name }}</p>
            </div>
        </div>
        <div class="row pb-1">
            <div class="col-md-6">
                <label>Last Name</label>
            </div>
            <div class="col-md-6">
                <p>{{ profile_details.last_name }}</p>
            </div>
        </div>
        <div class="row pb-1">
          <div class="col-md-6">
              <label>Gender</label>
          </div>
          <div class="col-md-6">
              <p>{{ profile_details.gender }}</p>
          </div>
      </div>
        <div class="row pb-1">
            <div class="col-md-6">
                <label>Email</label>
            </div>
            <div class="col-md-6">
                <p>{{ profile_details.user.email }}</p>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <label>Bio</label>
            </div>
            <div class="col-md-6">
                <p>{{ profile_details.bio}}</p>
            </div>
        </div>
        </div>
      </div>
    </div>
  </div>
  <div id = 'profile_update_form' class='row collapse'>
    <div class='col-lg-10'>
      <form method='POST'>
        {% csrf_token %}
        {{ u_form.as_p }}
        {{ p_form.as_p }}
        <button type="submit" class="btn btn-primary">Submit</button>
      </form>
    </div>
  </div>
</div>
{% endblock %}

users/templates/users/register.html
{% extends 'users/layout.html' %}

{% block title %}
    Register
{% endblock %}

{% block body %}
<div class="container-fluid pb-5">
    <div class="row no-gutter">
      <div class="d-none d-md-flex col-md-4 col-lg-6 my-auto">
        <div class="container masthead-content text-white py-5 py-md-0">
          <h1 class="display-4   mb-3 text-dark">Coming Soon!</h1>
          <h5 class=" mb-5 text-dark">We're working hard to finish the development of this site. Our target launch date is
            <strong>January 2021</strong>! Sign up for updates using the form below!</h5>
          <div class="form-inline">
            <input type="email" class="form-control" placeholder="Enter email..." aria-label="Enter email..." aria-describedby="submit-button">
            <div class="input-group-append">
              <button class="btn btn-secondary" type="button" id="submit-button">Notify Me!</button>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-8 col-lg-6">
        <div class="login d-flex align-items-center py-5">
          <div class="container">
            <div class="row">
              <div class="col-md-9 col-lg-8 mx-auto">
                <h3 class="login-heading mb-4">Welcome!</h3>
                {% if message %}
                    <div class="alert alert-danger" role="alert">{{ message }}</div>
                {% endif %}

                <form action="{% url 'users:register' %}" method="post">
                  {% csrf_token %}
                  <div class="form-group">
                    <input type="text" id="inputUsername" class="form-control" placeholder="Username" name='username' required>
                  </div>

                  <div class="form-group">
                    <input type="email" id="inputEmail" class="form-control" placeholder="Email address" name='email' required>
                  </div>
  
                  <div class="form-group">
                    <input type="password" id="inputPassword" class="form-control" placeholder="Password" name='password' required>
                    
                  </div>

                  <div class="form-group">
                    <input type="password" id="inputConfirmPassword" class="form-control" placeholder="Confirm Password" name="confirmation" required>
                  </div>
                  <!----<div class="form-group form-check">
                    <label class="form-check-label">
                      <input class="form-check-input" type="checkbox"> Agree To Terms and Conditions
                    </label>
                  </div>

                  <div class="form-group form-check">
                    <label class="form-check-label">
                      <input class="form-check-input" type="checkbox"> Remember Me?
                    </label>
                  </div>--->
                  <input class="btn btn-lg btn-primary btn-block btn-login text-uppercase font-weight-bold mb-2" type="submit" value='Sign Up'></input>
                  <div class='text-center'>Already have an account? <a href="{% url 'users:register' %}">Log In here.</a></div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}